version: '2'
services:
  web:
    build: .
    command: uwsgi --ini /uwsgi.ini --gid=1000 --uid=1000
    ports:
    - 8000:8000
    volumes:
    - /srv/data:/data
    depends_on: 
    - db
    environment:
     DATABASE_URL: postgres://postgres@db/postgres
  db:
    image: postgres:10.4
