# Generated by Django 3.0.7 on 2020-06-12 13:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='name')),
                ('image', models.ImageField(upload_to='wishes\\character', verbose_name='image')),
            ],
            options={
                'verbose_name': 'character',
                'verbose_name_plural': 'characters',
            },
        ),
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='text')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('published', models.BooleanField(default=False, verbose_name='published')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wishes.Character', verbose_name='author')),
            ],
            options={
                'verbose_name': 'wish',
                'verbose_name_plural': 'wishes',
            },
        ),
    ]
